### ISSUE TITLE
Add transaction fetching support

### ISSUE THREAD

**Issue by jeffsawatzky** [alexdlaird/amazon-orders#20]
### Acknowledgements

- [X] I have written a descriptive issue title
- [X] I have searched [Issues](issues?q=is%3Aissue) to see if the feature has already been requested
- [X] If relevant, I have [enabled `debug` mode](https://amazon-orders.readthedocs.io/en/latest/troubleshooting.html#enable-debug-mode) and am attaching relevant console logs and HTML files

### Describe the Feature

Can you add support to fetch transactions from the payments page:
https://www.amazon.ca/cpe/yourpayments/transactions

**Comment by jeffsawatzky** [comment]
Put up a PR #21 to add this.

**Comment by alexdlaird** [comment]
This has been released with `3.2.0`. Thanks!
